SAMPLES: config/samples.tsv

OUTPUT:
    REF: hg38
    RUN:
        QC: True
        PEAKS: True
        BWS: True
    SAECR_MODE: 
        - stringent
        - relaxed


# Reference Genome Settings
REFERENCES:
    hg38:
        FA: /groups/lackgrp/genomeAnnotations/hg38/hg38.fa
        BWA_IDX: /groups/lackgrp/genomeAnnotations/hg38/hg38.bwa.idx
        BOWTIE2_IDX: /groups/lackgrp/genomeAnnotations/hg38/hg38.bowtie2.idx/hg38
        CHROM_SIZES: /groups/lackgrp/genomeAnnotations/hg38/hg38.chrom.sizes
        BLACKLIST: /groups/lackgrp/genomeAnnotations/hg38/hg38-blacklist.v2.bed